const data = {
    products: [
        {
            name: 'Free Shirts',
            slug: 'free-shirts',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirts',
        },
       
        {
            name: 'Fit Shirts',
            slug: 'fit-shirts',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirts',
        },
       
        {
            name: 'Slim Shirts',
            slug: 'slim-shirts',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 90,
            brand: 'RAymond',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirts',
        },
       
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 90,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart looking pants',
        },
       
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 95,
            brand: 'Zara',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 75,
            brand: 'Clasely',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular classic pants',
        },
       
    ],
};
export default data;